name: Deploy to EC2 machine

on:
    push:
        branches:
            - main


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the code base
              uses: actions/checkout@v4

